### ISSUE TITLE
Requested module does not provide an export named 'UAParser'

### ISSUE THREAD

**Issue by wax911** [boywithkeyboard-archive/user_agent#1]
Hey there, so trying to use this in a project and I get this error after trying to run the script with this project import

```
error: Uncaught SyntaxError: The requested module 'https://cdn.jsdelivr.net/npm/ua-parser-js@1.0.34/dist/ua-parser.pack.js/+esm' does not provide an export named 'UAParser'
import { UAParser } from 'https://cdn.jsdelivr.net/npm/ua-parser-js@1.0.34/dist/ua-parser.pack.js/+esm'
```

I wonder if it's not better to replace the cdn for `UAParser` with esm instead: `https://esm.sh/ua-parser-js@1.0.34`

**Comment by boywithkeyboard** [comment]
I'm very sorry for the inconvenience and the late reply 😕. The problem should be fixed now with the latest version.

I've also added a simple test suite to avoid such issues in the future.

**Comment by boywithkeyboard** [comment]
@wax911, I should probably also note that I prefer jsdelivr over esm.sh because it doesn't try to make the NPM package compatible with Deno. esm.sh efforts sometimes insert unnecessary boilerplate into your production bundles, making it impossible to use the package in other environments like Cloudflare Workers or browsers.

**Comment by wax911** [comment]
> @wax911, I should probably also note that I prefer jsdelivr over esm.sh because it doesn't try to make the NPM package compatible with Deno. esm.sh efforts sometimes insert unnecessary boilerplate into your production bundles, making it impossible to use the package in other environments like Cloudflare Workers or browsers.

Thanks for the extra context, I wasn't aware of that limitations 😔
